### ISSUE TITLE
update row.names of the object

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#60]
When building fragmentation maps:

1) we can only build a proportion of conditions (say 200-300), since after the plot becomes non-interpretable
2) the full names really take a lot of space

my suggestion is this: lets introduce a function that updates names based on  sampleColumns. So if I have filtered an object to have the same AGC target I can just remove the AGCtarget from sampleColumns 

I understand its simply a matter of 

row.names (tds@colData) <- apply(as.data.frame(tds@colData[sampleColumns], stringsAsFactors = FALSE), 1, function(x) paste(x, collapse = "_"))

but it would be more elegant to just right

tds <- updateCondNames (tds, sampleColumns)

**Comment by sgibb** [comment]
You are right a function would be better because:

1. It is less error prone.
2. Most user wouldn't know how to set `row.names(tds@colData) <-`.
1. It could throw an error if non-unique names a generated. 
    Or it could add numbers to the end of the name to get unique names (as currently done in `readTopDownFiles`).

Instead of `row.names`/`col.names` we could provide better to remember functions: `conditionNames` as alias for `col.names` (we already have `conditionData` as alias for `colData`). But I am not sure how to name the `row.names` functions (I removed the `fragmentData` alias because its name is not correct for `NCBSet`s).

BTW: Currently we don't store the `sampleColumns` vector that is applied in `readTopDownFiles` in the object. So the user has to provide the column names himself.
BTW2: `MSnbase` has similar functions: `updateFeatureNames`, `updateSampleNames` and `updateFvarLabels`

**Comment by sgibb** [comment]
There is a new method `updateConditionNames(tds, sampleColumns)` that you could use (it automatically removes non-informative columns, in your example: if all AgcTargets are equal it just ignore this column).
